version: '3'

services:
    master:
        image: golang
        volumes:
            - ./:/go/src/github.com/goku321/line-racer
        command: [sh, -c, "go install github.com/goku321/line-racer && /go/bin/line-racer"]
        ports: [3000:3000/tcp]
    
    racer1:
        image: golang
        volumes:
            - ./:/go/src/github.com/goku321/line-racer
        command: [sh, -c, "go install github.com/goku321/line-racer && /go/bin/line-racer -nodeType racer -racerID 0 -port 4000 -ip racer1 -masterIP master"]
        ports: [4000:4000/tcp]
    
    racer2:
        image: golang
        volumes:
            - ./:/go/src/github.com/goku321/line-racer
        command: [sh, -c, "go install github.com/goku321/line-racer && /go/bin/line-racer -nodeType racer -racerID 1 -port 8000 -ip racer2 -masterIP master"]
        ports: [8000:8000/tcp]